### ISSUE TITLE
Access token failed

### ISSUE THREAD

**Issue by dahel** [2dvisio/cordova-plugin-googlefit#1]
Hi.
I'm trying to connect to Fitness API using this plugin.
I've enabled Fitness api in google console developer, genereted SHA-1 using
 `keytool -list -v -keystore degub.keystore` 
and added it to fingerprint list in developer console.
After calling 
`window.plugins.googlefit.getStuff1` 
nothing happens, no error or success callback is called.
I've noticed in logcat this message:
`V BaseAuthAsyncOperation: access token request failed: com.google.android.gms`
and i suppose this is the reason of failure.
Is it an plugin issue or my setup mistake?
Will be greatful for any help

**Comment by 2dvisio** [comment]
Are you sure you have added the Google Play services as expected in your gradle file? Also did you re-sync the gradle file?

**Comment by dahel** [comment]
i have in gradle:

```
dependencies {
     ...
    compile "com.google.android.gms:play-services:7.5.0+"
}
```

I also tried to resync, still getting this error.
Whats more i've tried to run Google Fit example app from:
https://github.com/googlesamples/android-fit/tree/master/BasicHistoryApi
 and got exactly the same error :/

**Comment by 2dvisio** [comment]
Have you also created the connection in the Google code console ?
You have to be sure that the application that you test is signed with the certificate that is installed in the Google code console, otherwise your app won't have the authorisation of reading the data out of Google Fit.
Hope this help.

**Comment by dahel** [comment]
It works now. 
I re-tried, use new keystore and go step by step in setup again.
It looks like i had some setup issue previously.
Thanks for response!
