### ISSUE TITLE
Android Build Issue

### ISSUE THREAD

**Issue by Chuckv01** [2dvisio/cordova-plugin-googlefit#3]
Is there something we should do to make this plugin compatible with other cordova plugins that may require the same frameworks? Getting a build error when trying to build on android:

:dexDebug
UNEXPECTED TOP-LEVEL EXCEPTION:
com.android.dex.DexException: Multiple dex files define Lcom/google/android/gms/internal/zzkd;
    at com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.java:579)
    at com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:535)
    at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:517)
    at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:164)
    at com.android.dx.merge.DexMerger.merge(DexMerger.java:188)
    at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:504)
    at com.android.dx.command.dexer.Main.runMonoDex(Main.java:334)
    at com.android.dx.command.dexer.Main.run(Main.java:277)
    at com.android.dx.command.dexer.Main.main(Main.java:245)
    at com.android.dx.command.Main.main(Main.java:106)

 FAILED

FAILURE: Build failed with an exception.

What went wrong:
Execution failed for task ':dexDebug'.

> com.android.ide.common.internal.LoggedErrorException: Failed to run command:
>     /Applications/Android Developer Tools/sdk/build-tools/23.0.2/dx --dex --no-optimize --output ...
>   Error Code:
>     2
>   Output:

```
UNEXPECTED TOP-LEVEL EXCEPTION:
com.android.dex.DexException: Multiple dex files define Lcom/google/android/gms/internal/zzkd;
    at com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.java:579)
    at com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:535)
    at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:517)
    at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:164)
    at com.android.dx.merge.DexMerger.merge(DexMerger.java:188)
    at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:504)
    at com.android.dx.command.dexer.Main.runMonoDex(Main.java:334)
    at com.android.dx.command.dexer.Main.run(Main.java:277)
    at com.android.dx.command.dexer.Main.main(Main.java:245)
    at com.android.dx.command.Main.main(Main.java:106)
```
- Try:
  Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

**Comment by 2dvisio** [comment]
Hi! what are the other plugins you are trying to run this with?

**Comment by Chuckv01** [comment]
Here's the plugin list:

com.ionic.keyboard 1.0.4 "Keyboard"
cordova-plugin-admobpro 2.9.8 "AdMob Plugin Pro"
cordova-plugin-ambient-sound 0.7.0 "AmbientSound"
cordova-plugin-console 1.0.1 "Console"
cordova-plugin-device 1.0.1 "Device"
cordova-plugin-dialogs 1.1.1 "Notification"
cordova-plugin-extension 1.1.6 "Cordova Plugin Extension"
cordova-plugin-file 3.0.0 "File"
cordova-plugin-geolocation 1.0.1 "Geolocation"
cordova-plugin-google-analytics 0.7.2 "Google Universal Analytics Plugin"
cordova-plugin-google-app-conversion-tracker 0.0.2 "GoogleAppTracking"
cordova-plugin-inappbrowser 1.0.1 "InAppBrowser"
cordova-plugin-media 1.0.2-dev "Media"
cordova-plugin-network-information 1.0.1 "Network Information"
cordova-plugin-splashscreen 2.1.0 "Splashscreen"
cordova-plugin-whitelist 1.0.0 "Whitelist"
cordova-plugin-x-socialsharing 5.0.5 "SocialSharing"
de.appplant.cordova.plugin.background-mode 0.6.4 "BackgroundMode"
de.appplant.cordova.plugin.email-composer 0.8.3dev "EmailComposer"
de.appplant.cordova.plugin.local-notification 0.8.2dev "LocalNotification"
nl.x-services.plugins.insomnia 4.0.1 "Insomnia (prevent screen sleep)"
uk.co.whiteoctober.cordova.appversion 0.1.7 "AppVersion"

Love this project by the way - I think it is an awesome idea and I hope it gains popularity :)

**Comment by 2dvisio** [comment]
Thanks for the support. 
Are you sure that with all those dependencies the problem is with the gfit package? Where does the stack trace points to gfit?

**Comment by 2dvisio** [comment]
I think the problem is that some other plugin is including a version of the Google Play Services that conflicts with that of my plug in. Any idea of how to get rid of that?

**Comment by array-addu** [comment]
Just comment the line compile 

> "com.google.android.gms:play-services:7.5.0+"
> in 
> 
> dependencies {
>     compile fileTree(dir: 'libs', include: '*.jar')
>     // SUB-PROJECT DEPENDENCIES START
>     debugCompile project(path: "CordovaLib", configuration: "debug")
>     releaseCompile project(path: "CordovaLib", configuration: "release")
>     compile "com.google.android.gms:play-services-fitness:9.4.0"
>    // compile "com.google.android.gms:play-services:7.5.0+"
>     // SUB-PROJECT DEPENDENCIES END
> }

 and add

> allprojects {     configurations {         all*.exclude group: 'com.android.support', module: 'support-v4'     } }

and add multiDexEnabled true to defaultConfig.

**Comment by 2dvisio** [comment]
Hi @array-addu 

I have been advised to just change the `plugin.xml` file and add substitute the play-services:7.5.0+ with just "com.google.android.gms:play-services-fitness:9.4.0" as you also seem to suggest.

Can you confirm that will fix the issues that @Chuckv01 is experiencing?

**Comment by array-addu** [comment]
Hi @2dvisio 

Yes, just need to add "com.google.android.gms:play-services-fitness:9.4.0", there is no need to add play-services and that issue will be resolved.

**Comment by array-addu** [comment]
Hi @2dvisio 
I'm testing this plugin in Meteor and till now am not able to get some data from this plugin. I've added all the necessary files required but when i compile the project` googlefit.getData() `doesn't return any success and error callback.

**Comment by array-addu** [comment]
Hi @2dvisio
I am facing a new error when running with android studio
Error:(99, 13) error: cannot find symbol variable TYPE_ACTIVITY_SAMPLES

**Comment by array-addu** [comment]
Hi  @2dvisio
I am facing app crash problem while running the code.
The error in event log is:
Could not find class 'org.apache.cordova.PluginEntry', referenced from method org.apache.cordova.ConfigXmlParser.handleEndTag.
