### ISSUE TITLE
Nothing happens, NO error or success callback is called.

### ISSUE THREAD

**Issue by firmusoft** [2dvisio/cordova-plugin-googlefit#4]
Using Genymotion and chrome://inspect to debug.

**ionic version - 1.7.14
platform - android
API Level - 19**

After calling
_window.plugins.googlefit.getStuff1_
nothing happens, no error or success callback is called.

Have followed all instructions and this is my code:
`window.plugins.googlefit.getStuff1(
                    startDate.getTime(), // quest begin date
                    new Date().getTime(), // now
                    ['com.google.step_count.delta']
                , function (value) {
                    $scope.stepsCount = value;
                }, function (err) {
                    $scope.stepsCount = 0;
                });`

No error or warning in console. App did ask for which account to use.

Also how to check if googlefit is available or not using this plugin?

PLEASE TREAT THIS AS URGENT. Quick help appreciated. Thanks!

**Comment by 2dvisio** [comment]
Did you configured your Google developer account so that you have the SHA signature of your certificate allowed for calls to the Google Fit API?
I just tested with the latest version of Cordova and it works as expected.

**Comment by firmusoft** [comment]
YES, all that in place.

**Comment by 2dvisio** [comment]
What version of Cordva is your ionic using?
I do not use ionic so you'll have to debug a bit more I guess...

**Comment by firmusoft** [comment]
cordova --version
6.0.0

**Comment by firmusoft** [comment]
Further, was using statusbar plugin to hide statusbar, after the _getStuff1_ call it becomes visible?

**Comment by 2dvisio** [comment]
No idea what is going on there :/ sorry

**Comment by rwvandenberg** [comment]
@firmusoft - I'm unfamiliar with Genymotion.

I'm successfully using the plug-in (specifically `getStuff1` in the following environment: 
- Android 6.0 (API 23)
- Cordova 6.0.0
- Ionic 1.7.14

I can successfully build to a device running Android 5.0.1 using `ionic build android`.

I have the Google Fit application installed on the phone and can see my app's name listed under:
-  "Fit --> Settings --> Connected Apps --> Google Fit apps & devices

If you haven't already done so, I suggest creating a stand-alone project containing nothing other than Carmelo's plug-in. Create a fresh app in the Google Developer console, configure it as described in the documentation and then report back.

Good luck!  
P.S., thank you @2dvisio for all of your efforts on this plug-in.

**Comment by 2dvisio** [comment]
You're welcome. As I said, I welcome contributions from anyone. So if you think that there are ways of improving or generalising the plug-in and you want to contribute, you are all more than welcome to do so! :)
