### ISSUE TITLE
Issue with Android 6.0 + permissions

### ISSUE THREAD

**Issue by brijendratiwari** [2dvisio/cordova-plugin-googlefit#5]
As I saw while building an app using your plugin in Marshmallow devices, it just crashes after requesting permission from Google Fit.

I have managed to fix it in my app for your plugin, if you need the fixes please contact.

**Comment by 2dvisio** [comment]
Hi @brijendratiwari and thanks for spotting the error.
Is there any possibility that you can create a pull request with the bugfix?
This will certainly help other users!

All the best

**Comment by brijendratiwari** [comment]
Hello,

I will test my fixes and then create the pull request by tomorrow.

Regards,

Brij

Sent from iCloud

On Jun 20, 2016, at 07:19 AM, Carmelo Velardo notifications@github.com wrote:

Hi @brijendratiwari and thanks for spotting the error.
Is there any possibility that you can create a pull request with the bugfix?
This will certainly help other users!

All the best

**Comment by 2dvisio** [comment]
That looks amazing. Thanks for your time!

**Comment by brijendratiwari** [comment]
I am going to generate a pull request, please check, if it has any issues then please resolve them if needed.

**Comment by 2dvisio** [comment]
All seems fine. Thank you @brijendratiwari !

**Comment by brijendratiwari** [comment]
You are most welcome @2dvisio
