### ISSUE TITLE
Incorrect daily steps

### ISSUE THREAD

**Issue by feruzm** [2dvisio/cordova-plugin-googlefit#9]
Hi,

When I access data for daily, steps are different than what googlefit has.
Any idea why?
Some interesting points here: https://stackoverflow.com/questions/32084380/google-fit-history-api-incorrect-values-for-steps
But not sure which one I should be using.

**Comment by 2dvisio** [comment]
Hello,

Which function are you using? Are you sure that you are doing the bucketing how the GFit does?

BW,
Carmelo

**Comment by feruzm** [comment]
I was using it something like this:

```
 window.plugins.googlefit.getStuff2(
      today.valueOf(),
      tomorrow.valueOf(),
      ['com.google.step_count.delta'],
      ['com.google.step_count.delta'],
      1,
      "DAYS",
      0,
      function (data) {
        var steps = {};

        _.each(data, function (d) {
          steps[d.start] = steps[d.start] || {}
          steps[d.start] = {
            start: d.start,
            end: d.end,
            steps: 0
          }

          _.each(d.datasets || [], function (set) {
            _.each(set, function (s) {
              steps[d.start].steps = _.reduce(s.fields, function (memo, field) {
                try {
                  field.value = parseInt(field.value, 10);
                } catch (e) {
                  field.value = 0
                }

                return memo + (field.value || 0);
              }, 0);
            });
          });
        });
      // return steps / save steps
});
```

**Comment by 2dvisio** [comment]
In all fairness, you should compare the results of the cordova plugin with that you obtain by a similar application written in Java.
The data you pass to the JS are passed AS IS to the Java functions.

For the moment I am closing this issue. In case you test JS vs. Java and you see a difference, let me know :)
